import path from "path";

export const paths = [
  { path: "", title: "Home" },
  // { path: "blog", title: "Articles" },
  { path: "plans", title: "Workouts Plans" },
  { path: "calculators", title: "Calculator" },
];

export const DUMMY_POSTS = [
  {
    id: 0,
    title: "Best protein sources",
    content:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?",
    snippet: "Let's check our propositions of best protein sources!",
    imagesrc: "/blog_images/post0.jpg",
  },
  {
    id: 1,
    title: "Best carbon sources",
    content:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?",
    imagesrc: "/blog_images/post0.jpg",
    snippet: "Let's check our propositions of best protein sources!",
  },
  {
    id: 2,
    title: "Best protein sources",
    content:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?",
    imagesrc: "/blog_images/post0.jpg",
    snippet: "Let's check our propositions of best protein sources!",
  },
  {
    id: 3,
    title: "Best protein sources",
    content:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab fugit repellat recusandae labore impedit cumque omnis ut illum vero distinctio? Sit distinctio qui rem officia nisi fuga iste, nostrum saepe?",
    imagesrc: "/blog_images/post0.jpg",
    snippet: "Let's check our propositions of best protein sources!",
  },
];
